# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a629f703a410a10442d0fceb54c52df3151cbbb6bd04a262a242fbc90fdf6634cdd38901a5e13c32da5ecfc852c98830302fc4c832f0d3ebeed279d0f2738a19

test:
  secret_key_base: fa9176588fd95db32b84fd54d1c595c5a35bec98b9bd73f292a9a55ae48f0e035f3fff211790d7f60784ff566f73fc579cac2ef05ac77c51fc8322d892b747bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
